import type { Metadata } from "next";
import { Gideon_Roman } from "next/font/google";
import "./globals.css";

const gideonRoman = Gideon_Roman({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gideonRoman.className} antialiased bg-black scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
